### ISSUE TITLE
Code Block

### ISSUE THREAD

**Issue by DarwinWasWrong** [arduinodiscord/bot-legacy#104]
Hi,
suggestion to change the code block to something more user friendly
![Capture33](https://user-images.githubusercontent.com/6262140/121848925-df619680-cd29-11eb-9c1a-edfe645dc080.JPG)

{
  "content": "To show your code here, \ncopy the section below, \nthen paste your code where indicated \n \n  \\```arduino\n\n YOUR CODE GOES HERE \n\n\\```\n\n",
  "embed": {
    "color": 3850630,
    "title": "If your code is over 2000 characters 😱 \n you will have to use a site to paste the code and share the link here.",
    "description": "Some of those sites are listed below",
   
    "color": 3850630,
    "timestamp": "2021-06-14T05:57:51.803Z",
    "footer": {
      "text": "Try and get it right 🙄"
    },
    "thumbnail": {
      "url": "https://cdn.discordapp.com/embed/avatars/0.png"
    },
    
    "author": {
      "name": "Arduino Bot"
      },
    "fields": [
      {
        "name": "hastebin",
        "value": "https://hastbin.com"        
      },
      {
        "name": "pastebin",
        "value": "https://pastbin.com"
      },
      {
        "name": " ubuntu paste",
        "value": "https://paste.ubuntu.com/"
      },
      {
        "name": "gits github com    __note: you need an account__",
        "value": "https://gits.github.com",
        "inline": false
      }
    ]
  }
}

**Comment by DarwinWasWrong** [comment]
https://pastebin.com/FxjEdJwv

Better

**Comment by prakulkhebbur** [comment]
Hey in a few days this will be removed i guess as Discord's new rich text view is great !

**Comment by DarwinWasWrong** [comment]
isnt the same as  pretty \```arduino  \```
