### ISSUE TITLE
feat: spam/duplicate detection

### ISSUE THREAD

**Issue by alexanderl19** [arduinodiscord/bot-legacy#67]
**Is your feature request related to a problem? Please describe.**
Often, people post the same problem in multiple help channels. Ideally, we would have an automated way of detecting and preventing this.

**Describe the solution you'd like**
Have the bot reference messages sent from the user in the other help channel and general to see if they are similar/copy pasted.

**Describe alternatives you've considered**

**Additional context**

**Comment by max-bromberg** [comment]
This will likely be wrapped up in the implementation of #43, whatever that is.
